version: "2.1"
services:
  mstream:
    image: lscr.io/linuxserver/mstream:latest
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /opt/mstream/data:/config
      - /opt/mstream/media:/music
    ports:
      - 3000:3000
    restart: unless-stopped
