version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    group_add:
      - "109"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=192.168.1.36
    volumes:
      - /opt/jellyfin/library:/config
      - /opt/jellyfin/tvseries:/data/tvshows
      - /opt/jellyfin/movies:/data/movies
      - /opt/jellyfin/transcodes:/transcode
      - /opt/jellyfin/media:/data/media
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1902:1900/udp #optional
    restart: unless-stopped
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
